# manual_prompts = {
#     'KSDD2': [
#         ['black hole.', 'ksdd2'],
#         ['defect.', 'ksdd2'],
#     ],

# }

# property_prompts = {
#     'KSDD2': 'the image of ksdd2 have 1 dissimilar ksdd2, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ',
# }


manual_prompts = {'ksdd1': [
        ['black hole.', 'ksdd'], 
        ['defect.', 'ksdd']
        ], 
    'kos01': [
        ['black hole.', 'ksdd'], 
        ['defect.', 'ksdd']
        ], 
    'kos02': [
        ['black hole.', 'ksdd'], 
        ['defect.', 'ksdd']
        ], 
    'kos03': [
        ['black hole.', 'ksdd'], 
        ['defect.', 'ksdd']
        ], 
    'kos04': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos05': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos06': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos07': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos08': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos09': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos10': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos11': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos12': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos13': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos14': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos15': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos16': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos17': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos18': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos19': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos20': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos21': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos22': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos23': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos24': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos25': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos26': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos27': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos28': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos29': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos30': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos31': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos32': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos33': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos34': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos35': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos36': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos37': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos38': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos39': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos40': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos41': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos42': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos43': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos44': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos45': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos46': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos47': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos48': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos49': [['black hole.', 'ksdd'], ['defect.', 'ksdd']], 
    'kos50': [['black hole.', 'ksdd'], ['defect.', 'ksdd']]
    }

property_prompts = {
    'ksdd1': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ',
    'kos01': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos02': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos03': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos04': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos05': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos06': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos07': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos08': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos09': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos10': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos11': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos12': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos13': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos14': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos15': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos16': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos17': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos18': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos19': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos20': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos21': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos22': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos23': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos24': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos25': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos26': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos27': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos28': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos29': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos30': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos31': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos32': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos33': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos34': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos35': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos36': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos37': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos38': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos39': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos40': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos41': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos42': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos43': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos44': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos45': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos46': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos47': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos48': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos49': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. ', 
    'kos50': 'the image of ksdd have 1 dissimilar ksdd, with a maximum of 5 anomaly. The anomaly would not exceed 0.9 object area. '
    }